-- AlterTable
ALTER TABLE `cita` MODIFY `Modalidad` ENUM('PRESENCIAL', 'VIRTUAL', 'HIBRIDA', 'NOCAP') NOT NULL DEFAULT 'PRESENCIAL';

-- AlterTable
ALTER TABLE `servicio` MODIFY `Modalidad` ENUM('PRESENCIAL', 'VIRTUAL', 'HIBRIDA', 'NOCAP') NOT NULL DEFAULT 'PRESENCIAL';

-- AlterTable
ALTER TABLE `usuario` MODIFY `Modalidad` ENUM('PRESENCIAL', 'VIRTUAL', 'HIBRIDA', 'NOCAP') NULL DEFAULT 'NOCAP';
